
import { Request, Response, NextFunction } from 'express';
import PDFDocument from 'pdfkit';
import QRCode from 'qrcode';
import Order from '../models/orderModel';
import Seller from '../models/sellerModel';
import { catchAsync } from '../utils/catchAsync';
import { AppError } from '../utils/AppError';

/**
 * Shipping Controller
 * 
 * Handles generation of printable shipping labels in PDF format.
 * Labels include:
 * - Sender Info (Seller Store Name & Details)
 * - Receiver Info (Shipping Address)
 * - Order Details (Order Number, Date)
 * - Item Summary (Seller's items only)
 * - Tracking QR Code
 */

/**
 * @desc    Generate Shipping Label PDF
 * @route   GET /api/v1/shipping/label/:orderId
 * @access  Private/Seller
 * 
 * Generates a professional shipping label PDF.
 * If multi-vendor, the label only lists items from the requesting seller.
 */
export const generateShippingLabel = catchAsync(async (req: Request, res: Response, next: NextFunction) => {
    const sellerId = req.user!._id;
    const { orderId } = req.params;

    // 1. Fetch Order and Seller Profile
    const [order, seller] = await Promise.all([
        Order.findById(orderId),
        Seller.findOne({ user: sellerId })
    ]);

    if (!order) {
        return next(new AppError('Order not found', 404));
    }

    if (!seller) {
        return next(new AppError('Seller profile not found', 404));
    }

    // 2. Validate Ownership (Order must contain items from this seller)
    const sellerItems = order.items.filter(item => item.seller.toString() === sellerId.toString());
    if (sellerItems.length === 0 && req.user!.role !== 'admin') {
        return next(new AppError('Not authorized to generate label for this order', 403));
    }

    // 3. Generate tracking QR Code (base64)
    const qrCodeDataUrl = await QRCode.toDataURL(order.orderNumber, { margin: 1 });

    // 4. Create PDF Document
    const doc = new PDFDocument({
        size: [288, 432], // 4x6 inch label size (standard for shipping)
        margin: 20
    });

    // 5. Set response headers
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=label-${order.orderNumber}.pdf`);

    // 6. Pipe PDF to response
    doc.pipe(res);

    // --- PDF Content ---

    // Header: SHIP TO
    doc.fontSize(10).font('Helvetica-Bold').text('SHIP TO:');
    doc.fontSize(12).font('Helvetica').text(order.shippingAddress.fullName);
    doc.fontSize(10).text(order.shippingAddress.addressLine1);
    if (order.shippingAddress.addressLine2) {
        doc.text(order.shippingAddress.addressLine2);
    }
    doc.text(`${order.shippingAddress.city}, ${order.shippingAddress.state} - ${order.shippingAddress.postalCode}`);
    doc.text(`Phone: ${order.shippingAddress.phone}`);

    doc.moveDown();
    doc.moveTo(20, doc.y).lineTo(268, doc.y).stroke();
    doc.moveDown();

    // From: SELLER
    doc.fontSize(10).font('Helvetica-Bold').text('FROM:');
    doc.fontSize(11).font('Helvetica').text(seller.storeName);
    doc.fontSize(9).text(seller.businessDetails.address);
    doc.text(`Phone: ${req.user!.email}`); // Using user email as contact if phone is private

    doc.moveDown();
    doc.moveTo(20, doc.y).lineTo(268, doc.y).stroke();
    doc.moveDown();

    // Order Details
    doc.fontSize(10).font('Helvetica-Bold').text(`ORDER: ${order.orderNumber}`);
    doc.fontSize(9).font('Helvetica').text(`Order Date: ${order.createdAt.toLocaleDateString()}`);

    doc.moveDown(0.5);
    doc.fontSize(10).font('Helvetica-Bold').text('ITEMS:');
    sellerItems.forEach(item => {
        doc.fontSize(9).font('Helvetica').text(`• ${item.name} x ${item.quantity}`);
    });

    // Footer: QR Code and Branding
    const qrSize = 80;
    doc.image(qrCodeDataUrl, 288 - qrSize - 20, 432 - qrSize - 20, { width: qrSize });

    doc.fontSize(8)
        .fillColor('grey')
        .text('Generated by Antigravity Marketplace', 20, 432 - 30);

    // 7. Finalize PDF
    doc.end();
});
